(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const ACCOUNT_KEY='URW_ACCOUNT_V1',SESSION_KEY='URW_SESSION_V1',PROJECTS_KEY='URW_PROJECTS_V1';
const ETNIKA={id:'etnika',name:'Студия автопортрета Этника',sourceUrl:'https://yandex.ru/maps/org/studiya_avtoportreta_etnika/136853819595/reviews/',businessId:'136853819595',slug:'studiya_avtoportreta_etnika',status:'live',createdAt:'2026-09-25T00:00:00Z'};
let etnikaStats={rating:'—',reviews:'—',updated:'—'};
function read(k,f=null){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
async function hash(v){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function session(){return read(SESSION_KEY)}
function account(){return read(ACCOUNT_KEY)}
function projects(){let p=read(PROJECTS_KEY);if(!Array.isArray(p)||!p.length){p=[ETNIKA];write(PROJECTS_KEY,p)}else if(!p.some(x=>x.id==='etnika')){p.unshift(ETNIKA);write(PROJECTS_KEY,p)}return p}
function saveProjects(p){write(PROJECTS_KEY,p)}
function parseYandex(value){try{const u=new URL(String(value||'').trim());if(!/(^|\.)yandex\.(ru|com)$/i.test(u.hostname))return null;const m=u.pathname.match(/\/maps\/org\/([^/]+)\/(\d+)/i);if(!m)return null;return {slug:decodeURIComponent(m[1]),businessId:m[2],sourceUrl:`https://yandex.ru/maps/org/${m[1]}/${m[2]}/reviews/`}}catch{return null}}
function slug(s){return String(s||'project').toLowerCase().replace(/[ё]/g,'е').replace(/[^a-zа-я0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,32)||'project'}
function projectById(id){return projects().find(p=>p.id===id)}
function route(){const h=location.hash.replace(/^#/,'')||'projects';const path=h.split('?')[0];const [a,b]=path.split('/');return {page:a,id:b}}
function setRoute(v){location.hash=v}
async function loadStats(){try{const r=await fetch('./data/projects/etnika.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)return;const j=await r.json();etnikaStats={rating:j.summary?.rating??'—',reviews:j.summary?.reviewsCount??j.reviews?.length??'—',updated:j.fetchedAt?new Date(j.fetchedAt).toLocaleString('ru-RU'):'—'}}catch{}}
function authHtml(){return `<div class="auth"><section class="auth-art"><div class="logo">REVIEWS</div><div class="auth-copy"><h1>Отзывы на сайте.<br>Под вашим контролем.</h1><p>Подключайте Яндекс Карты, управляйте дизайном, отзывами и установкой каждого проекта из одного кабинета.</p></div><div class="auth-note">ETNIKA — первый тестовый проект</div></section><section class="auth-panel"><div class="auth-box"><div class="auth-tabs"><button class="auth-tab on" data-auth="login">Войти</button><button class="auth-tab" data-auth="register">Регистрация</button></div><form id="authForm"><div class="field register-only hidden"><label>Имя</label><input id="authName" autocomplete="name"></div><div class="field"><label>Email</label><input id="authEmail" type="email" required autocomplete="email"></div><div class="field"><label>Пароль</label><input id="authPassword" type="password" required minlength="6" autocomplete="current-password"></div><button class="btn dark auth-submit" type="submit">Войти</button><div id="authError" class="error"></div></form><div class="proto">Сейчас это локальный прототип кабинета: аккаунт и проекты хранятся только в этом браузере. После подключения российского сервера этот же интерфейс перейдёт на реальную авторизацию и базу данных.</div></div></section></div>`}
function shell(inner,active='projects'){const a=account()||{};return `<div class="shell"><aside class="sidebar"><div class="logo">REVIEWS</div><nav class="nav"><button data-go="projects" class="${active==='projects'?'on':''}">Мои проекты</button><button data-go="subscription" class="${active==='subscription'?'on':''}">Подписка</button><button data-go="account" class="${active==='account'?'on':''}">Аккаунт</button></nav><div class="account"><div class="account-name">${esc(a.name||'Пользователь')}</div><div class="account-email">${esc(a.email||'')}</div><button class="logout" id="logout">Выйти</button></div></aside><main class="main">${inner}</main></div>`}
function projectsPage(){const list=projects();const cards=list.map(p=>{const live=p.status==='live';const st=p.id==='etnika'?etnikaStats:{rating:'—',reviews:'—',updated:'После подключения сервера'};return `<article class="project-card" data-open="${esc(p.id)}"><div class="project-top"><div><div class="project-name">${esc(p.name)}</div><div class="project-meta">Яндекс Карты<br>${esc(p.businessId||'Источник ещё не опубликован')}</div></div><span class="status ${live?'live':'local'}">${live?'Работает':'Локальный'}</span></div><div class="project-stats"><div class="stat"><strong>${esc(st.rating)}</strong><span>рейтинг</span></div><div class="stat"><strong>${esc(st.reviews)}</strong><span>отзывов</span></div></div><div class="project-actions"><button class="btn small dark" data-open-btn="${esc(p.id)}">Открыть</button></div></article>`}).join('');return shell(`<div class="topbar"><div><div class="eyebrow">Кабинет</div><h1 class="page-title">Мои проекты</h1></div><div class="top-actions"><button class="btn primary" id="newProject">+ Новый проект</button></div></div><section class="grid">${cards||'<div class="empty">Проектов пока нет.</div>'}</section>`,'projects')}
function accountPage(){const a=account()||{};return shell(`<div class="topbar"><div><div class="eyebrow">Настройки</div><h1 class="page-title">Аккаунт</h1></div></div><section class="panel"><h3>Профиль</h3><div class="settings-grid"><div class="field"><label>Имя</label><input id="profileName" value="${esc(a.name||'')}"></div><div class="field"><label>Email</label><input value="${esc(a.email||'')}" disabled></div></div><button class="btn dark" id="saveProfile">Сохранить</button></section><section class="panel" style="margin-top:16px"><h3>Хранение данных</h3><div class="notice warn">До подключения российского сервера аккаунт существует только в текущем браузере. Это не полноценная защищённая авторизация.</div></section>`,'account')}
function subscriptionPage(){return shell(`<div class="topbar"><div><div class="eyebrow">Тариф и оплата</div><h1 class="page-title">Подписка</h1></div><span class="status live">Beta</span></div><section class="panel"><h3>Текущий тариф</h3><div class="settings-grid"><div class="notice good"><b>Beta · 0 ₽</b><br>Тестовый доступ активен. Карта не требуется.</div><div class="notice"><b>Лимит сейчас не применяется.</b><br>ETNIKA и локальные тестовые проекты можно использовать во время беты.</div></div><button class="btn dark" disabled>Оплата откроется перед публичным запуском</button></section><section class="panel" style="margin-top:16px"><h3>Как будет работать оплата</h3><div class="notice">Оплата подписки будет приниматься через российский платёжный сервис: российская банковская карта и/или СБП. Точный провайдер подключим вместе с серверной частью, чтобы платежи, тариф и доступ к проектам управлялись автоматически.</div></section><section class="panel" style="margin-top:16px"><h3>История платежей</h3><div class="notice">Платежей пока нет — действует бесплатный Beta-доступ.</div></section>`,'subscription')}
function tabs(id,on){return `<div class="project-tabs"><button class="project-tab ${on==='overview'?'on':''}" data-ptab="overview">Обзор</button><button class="project-tab ${on==='editor'?'on':''}" data-ptab="editor">Редактор</button><button class="project-tab ${on==='install'?'on':''}" data-ptab="install">Установка</button><button class="project-tab ${on==='settings'?'on':''}" data-ptab="settings">Настройки</button></div>`}
function projectPage(p,tab='overview'){const live=p.status==='live';let body='';if(tab==='overview'){body=live?`<section class="panel"><h3>Состояние проекта</h3><div class="settings-grid"><div class="notice good"><b>Источник подключён.</b><br>Рейтинг: ${esc(etnikaStats.rating)} · Отзывов: ${esc(etnikaStats.reviews)}<br>Последняя синхронизация: ${esc(etnikaStats.updated)}</div><div class="notice"><b>Виджет опубликован.</b><br>Код установки постоянный. Новые отзывы подтягиваются автоматически.</div></div></section><section class="panel"><h3>Предпросмотр</h3><div class="preview-frame"><div data-reviews-project="etnika"></div></div></section>`:`<section class="panel"><h3>Состояние проекта</h3><div class="notice warn"><b>Проект создан локально.</b> Подключение автоматической синхронизации и публикация появятся после переноса кабинета на сервер.</div></section>`}
if(tab==='editor'){body=live?`<iframe class="editor-frame" src="builder.html?project=${encodeURIComponent(p.id)}"></iframe>`:`<section class="panel"><h3>Редактор</h3><div class="notice warn">Для нового проекта редактор реальных отзывов включится после серверной регистрации проекта. Сейчас сохранены название и источник, но сервер ещё не может синхронизировать эту организацию.</div></section>`}
if(tab==='install'){const code=`<div data-reviews-project="${p.id}"></div>\n<script src="https://nkuchenov-hash.github.io/reviews-widget/embed.js" defer><\/script>`;body=`<section class="panel"><h3>Код для сайта</h3><div class="notice ${live?'good':'warn'}">${live?'Этот код уже работает. Вставьте его один раз в HTML-блок сайта.':'Код проекта сформирован, но начнёт работать после публикации проекта на сервере.'}</div><pre class="embed-code" id="embedCode">${esc(code)}</pre><div class="copy-row"><button class="btn dark" id="copyEmbed">Скопировать код</button>${live?'<a class="btn" style="display:inline-flex;align-items:center;text-decoration:none;color:#111" href="demo-etnika.html" target="_blank">Открыть демо</a>':''}</div></section>`}
if(tab==='settings'){body=`<section class="panel"><h3>Проект</h3><div class="field"><label>Название</label><input id="projectName" value="${esc(p.name)}"></div><div class="connection"><div class="field"><label>Ссылка на организацию в Яндекс Картах</label><input id="projectSource" value="${esc(p.sourceUrl||'')}"></div><button class="btn dark" id="saveProjectSettings">Сохранить</button></div><div class="help">Вставляйте полную ссылку вида yandex.ru/maps/org/.../123456/reviews/</div>${p.id!=='etnika'?'<button class="btn danger" id="deleteProject" style="margin-top:24px">Удалить проект</button>':''}</section>`}
return shell(`<div class="topbar"><div><div class="eyebrow"><button class="btn small" id="backProjects">← Все проекты</button></div><h1 class="page-title">${esc(p.name)}</h1></div><span class="status ${live?'live':'local'}">${live?'Опубликован':'Локальный проект'}</span></div><section class="project-head"><div><h2>${esc(p.name)}</h2><div class="project-url">${esc(p.sourceUrl||'Источник не указан')}</div></div>${live?'<button class="btn dark" id="openEditor">Редактировать виджет</button>':''}</section>${tabs(p.id,tab)}<div class="project-view">${body}</div>`,'projects')}
function newProjectModal(){return `<div class="modal-backdrop" id="modal"><div class="modal"><h2>Новый проект</h2><div class="field"><label>Название проекта</label><input id="newName" placeholder="Например: Салон на Тверской"></div><div class="field"><label>Ссылка на организацию в Яндекс Картах</label><input id="newUrl" placeholder="https://yandex.ru/maps/org/..."></div><div id="newError" class="error"></div><div class="modal-actions"><button class="btn" id="cancelNew">Отмена</button><button class="btn dark" id="createProject">Создать проект</button></div></div></div>`}
async function bindAuth(){let mode='login';$$('.auth-tab').forEach(b=>b.onclick=()=>{mode=b.dataset.auth;$$('.auth-tab').forEach(x=>x.classList.toggle('on',x===b));$('.register-only').classList.toggle('hidden',mode!=='register');$('.auth-submit').textContent=mode==='register'?'Создать аккаунт':'Войти';$('#authPassword').autocomplete=mode==='register'?'new-password':'current-password';$('#authError').textContent=''});$('#authForm').onsubmit=async e=>{e.preventDefault();const email=$('#authEmail').value.trim().toLowerCase(),pw=$('#authPassword').value,name=$('#authName').value.trim();const err=$('#authError');if(pw.length<6){err.textContent='Пароль — минимум 6 символов.';return}if(mode==='register'){if(account()){err.textContent='Локальный аккаунт уже создан. Используйте «Войти».';return}write(ACCOUNT_KEY,{email,name:name||email.split('@')[0],passwordHash:await hash(pw),createdAt:new Date().toISOString()});write(PROJECTS_KEY,[ETNIKA]);write(SESSION_KEY,{email,at:Date.now()});setRoute('projects');render()}else{const a=account();if(!a||a.email!==email||a.passwordHash!==await hash(pw)){err.textContent='Неверный email или пароль.';return}write(SESSION_KEY,{email,at:Date.now()});setRoute('projects');render()}}}
function bindShell(){$$('[data-go]').forEach(b=>b.onclick=()=>setRoute(b.dataset.go));$('#logout')?.addEventListener('click',()=>{localStorage.removeItem(SESSION_KEY);location.hash='';render()})}
function bindProjects(){bindShell();$('#newProject').onclick=()=>{document.body.insertAdjacentHTML('beforeend',newProjectModal());$('#cancelNew').onclick=()=>$('#modal').remove();$('#createProject').onclick=()=>{const name=$('#newName').value.trim(),parsed=parseYandex($('#newUrl').value);if(!name){$('#newError').textContent='Введите название проекта.';return}if(!parsed){$('#newError').textContent='Не удалось определить организацию по ссылке Яндекса.';return}const list=projects();let id=slug(name);if(list.some(x=>x.id===id))id+='-'+Math.random().toString(36).slice(2,6);list.push({id,name,...parsed,status:'local',createdAt:new Date().toISOString()});saveProjects(list);$('#modal').remove();render()}};$$('[data-open],[data-open-btn]').forEach(el=>el.onclick=e=>{e.stopPropagation();setRoute('project/'+(el.dataset.open||el.dataset.openBtn))})}
function bindAccount(){bindShell();$('#saveProfile').onclick=()=>{const a=account();a.name=$('#profileName').value.trim()||a.name;write(ACCOUNT_KEY,a);toast('Профиль сохранён');render()}}
function loadEmbed(){if(window.UniversalReviewsEmbed){window.UniversalReviewsEmbed.mountProject?.('[data-reviews-project]','etnika');return}const s=document.createElement('script');s.src='./embed.js?v='+Date.now();s.defer=true;document.head.appendChild(s)}
function bindProject(p,tab){bindShell();$('#backProjects').onclick=()=>setRoute('projects');$$('[data-ptab]').forEach(b=>b.onclick=()=>{history.replaceState(null,'','#project/'+p.id+'?tab='+b.dataset.ptab);render()});$('#openEditor')?.addEventListener('click',()=>{history.replaceState(null,'','#project/'+p.id+'?tab=editor');render()});if(tab==='overview'&&p.id==='etnika')setTimeout(loadEmbed,0);$('#copyEmbed')?.addEventListener('click',async()=>{await navigator.clipboard.writeText($('#embedCode').textContent);toast('Код скопирован')});$('#saveProjectSettings')?.addEventListener('click',()=>{const list=projects(),i=list.findIndex(x=>x.id===p.id),name=$('#projectName').value.trim(),parsed=parseYandex($('#projectSource').value);if(!name){toast('Введите название');return}if(!parsed){toast('Неверная ссылка Яндекс Карт');return}list[i]={...list[i],name,...parsed};saveProjects(list);toast('Настройки сохранены');render()});$('#deleteProject')?.addEventListener('click',()=>{if(!confirm('Удалить этот проект из локального кабинета?'))return;saveProjects(projects().filter(x=>x.id!==p.id));setRoute('projects')})}
async function render(){const root=$('#root');if(!session()){root.innerHTML=authHtml();bindAuth();return}const r=route();if(r.page==='projects'){root.innerHTML=projectsPage();bindProjects();return}if(r.page==='subscription'){root.innerHTML=subscriptionPage();bindShell();return}if(r.page==='account'){root.innerHTML=accountPage();bindAccount();return}if(r.page==='project'){const p=projectById(r.id);if(!p){setRoute('projects');return}const q=new URLSearchParams((location.hash.split('?')[1]||''));const tab=q.get('tab')||'overview';root.innerHTML=projectPage(p,tab);bindProject(p,tab);return}setRoute('projects')}
window.addEventListener('hashchange',render);(async()=>{await loadStats();render()})();
})();