const $=id=>document.getElementById(id);
const sampleReviews=[
{id:'demo1',author:'Анна',rating:5,date:'2026-09-20',source:'yandex',text:'Очень понравился формат. Всё спокойно, красиво и без ощущения обычной фотосессии.',pinned:true,pinOrder:1},
{id:'demo2',author:'Мария',rating:5,date:'2026-09-16',source:'yandex',text:'Получились именно те кадры, которые хотелось. Отдельно понравилось, что можно не спешить и самой выбирать момент.',pinned:false},
{id:'demo3',author:'Екатерина',rating:5,date:'2026-09-09',source:'twogis',text:'Интерьер, свет и сам процесс очень продуманы. Вернулась бы ещё раз уже с другим образом.',pinned:false},
{id:'demo4',author:'Ольга',rating:4,date:'2026-08-30',source:'google',text:'Удобный формат и хороший результат. Быстро разобралась, как всё работает.',pinned:false},
{id:'demo5',author:'Алина',rating:5,date:'2026-08-24',source:'yandex',text:'Редкий случай, когда на фотографиях нравишься себе почти сразу. Очень комфортный опыт.',pinned:false}
];
const defaults={source:{type:'manual',businessId:'226327670406',businessUrl:'https://yandex.ru/maps/org/usadba_izmaylovo/226327670406/'},design:{layout:'slider',columns:3,gap:18,radius:12,maxWidth:1200,fontFamily:'Inter,Arial,sans-serif',titleFontFamily:'Inter,Arial,sans-serif',titleSize:38,bodySize:16,cardPadding:22,buttonRadius:0,borderWidth:1,minRating:1,accent:'#111111',background:'#ffffff',cardBackground:'#ffffff',textColor:'#171717',mutedColor:'#777777',borderColor:'#e7e7e7',starColor:'#f2b01e',showAvatar:true,showDate:true,showSource:true,showSummary:true,autoplay:true,yandexHeight:620},content:{title:'Отзывы клиентов',subtitle:'Что говорят о нас',buttonText:'Оставить отзыв',buttonUrl:'',showHeader:true},reviews:sampleReviews};
let data=structuredClone(defaults),inst;const STATIC_MODE=location.hostname.endsWith('github.io')||location.protocol==='file:';
function storageKey(){return 'URW_WIDGET_demo'}function api(){return '/api/admin/widget/demo'}function tokenHeaders(){const t=localStorage.getItem('URW_ADMIN_TOKEN')||'';return {'Content-Type':'application/json',...(t?{'X-Admin-Token':t}:{})}}
async function load(){try{if(STATIC_MODE){const saved=localStorage.getItem(storageKey());data=saved?JSON.parse(saved):structuredClone(defaults);if(!Array.isArray(data.reviews)||!data.reviews.length)data.reviews=structuredClone(sampleReviews);fill();render();setStatus(saved?'Загружено из этого браузера.':'Демо-виджет готов к настройке.','ok');return}const r=await fetch(api(),{headers:tokenHeaders()});if(r.status===404){data=structuredClone(defaults);await save(false)}else{if(!r.ok)throw new Error(`HTTP ${r.status}`);data=await r.json()}fill();render();setStatus('Загружено.','ok')}catch(e){setStatus(e.message,'err')}}
async function save(show=true){collect();if(STATIC_MODE){localStorage.setItem(storageKey(),JSON.stringify(data));if(show)setStatus('Сохранено в этом браузере.','ok');fill();render();return}const r=await fetch(api(),{method:'PUT',headers:tokenHeaders(),body:JSON.stringify(data)});if(!r.ok)throw new Error((await r.json()).error||`HTTP ${r.status}`);data=await r.json();if(show)setStatus('Сохранено.','ok');fill();render()}
async function sync(){try{if(STATIC_MODE){setStatus(data.source.type==='yandex-live'?'Yandex Live обновляется самим Яндексом.':'Для реальной авто-синхронизации нужен backend. Сейчас это конструктор и рабочий embed.','err');return}await save(false);const r=await fetch(api()+'/sync',{method:'POST',headers:tokenHeaders()});const j=await r.json();if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);data=j;fill();render();setStatus('Синхронизировано.','ok')}catch(e){setStatus(e.message,'err')}}
function setStatus(s,c=''){const el=$('status');el.textContent=s;el.className='status '+c}
const designKeys=['layout','columns','radius','gap','maxWidth','cardPadding','borderWidth','buttonRadius','minRating','fontFamily','titleFontFamily','titleSize','bodySize','accent','background','cardBackground','textColor','borderColor','starColor','yandexHeight'];
function fill(){const s=data.source||{},d={...defaults.design,...(data.design||{})},c={...defaults.content,...(data.content||{})};$('sourceType').value=s.type||'manual';$('businessId').value=s.businessId||'';$('businessUrl').value=s.businessUrl||'';$('jsonUrl').value=s.url||'';$('syncEveryMinutes').value=s.syncEveryMinutes||60;designKeys.forEach(k=>{if($(k))$(k).value=d[k]});['showAvatar','showDate','showSource','showSummary','autoplay'].forEach(k=>$(k).checked=Boolean(d[k]));['title','subtitle','buttonText','buttonUrl'].forEach(k=>$(k).value=c[k]||'');sourceUI();reviewsUI()}
function collect(){data.source={...(data.source||{}),type:$('sourceType').value,businessId:$('businessId').value.trim(),businessUrl:$('businessUrl').value.trim(),url:$('jsonUrl').value.trim(),syncEveryMinutes:Math.max(5,Number($('syncEveryMinutes').value)||60)};data.design={...(data.design||{}),layout:$('layout').value,columns:Number($('columns').value),radius:Number($('radius').value),gap:Number($('gap').value),maxWidth:Number($('maxWidth').value),cardPadding:Number($('cardPadding').value),borderWidth:Number($('borderWidth').value),buttonRadius:Number($('buttonRadius').value),minRating:Number($('minRating').value),fontFamily:$('fontFamily').value,titleFontFamily:$('titleFontFamily').value,titleSize:Number($('titleSize').value),bodySize:Number($('bodySize').value),accent:$('accent').value,background:$('background').value,cardBackground:$('cardBackground').value,textColor:$('textColor').value,borderColor:$('borderColor').value,starColor:$('starColor').value,yandexHeight:Number($('yandexHeight').value),showAvatar:$('showAvatar').checked,showDate:$('showDate').checked,showSource:$('showSource').checked,showSummary:$('showSummary').checked,autoplay:$('autoplay').checked};data.content={...(data.content||{}),title:$('title').value,subtitle:$('subtitle').value,buttonText:$('buttonText').value,buttonUrl:$('buttonUrl').value,showHeader:true}}
function sourceUI(){const t=$('sourceType').value,isY=t==='yandex-live';$('yandexFields').style.display=isY?'block':'none';$('jsonFields').style.display=t==='json'?'block':'none';$('managedInfo').style.display=isY?'none':'block';$('reviewsDisabled').style.display=isY?'block':'none';$('reviewList').style.display=isY?'none':'grid';$('designLimit').style.display=isY?'block':'none';$('yandexHeightField').style.display=isY?'grid':'none';document.querySelectorAll('.managedOnly').forEach(el=>el.classList.toggle('disabled',isY));$('modeBadge').textContent=isY?'Yandex iframe · ограниченный дизайн':'Полный дизайн';$('modeBadge').classList.toggle('limited',isY)}
function reviewsUI(){const list=$('reviewList'),rs=data.reviews||[];list.innerHTML=rs.length?rs.map((r,i)=>`<div class="review ${r.hidden?'hidden':''} ${r.pinned?'pinned':''}"><div class="review-head"><div><div class="review-author">${escapeHtml(r.author||'Клиент')} · ${Number(r.rating||0)}★</div><div class="review-meta">${escapeHtml(r.date||'')} · ${escapeHtml(r.source||'custom')}</div></div><b>${r.pinned?'PIN':''}</b></div><div class="review-text">${escapeHtml(r.text||'')}</div><div class="review-actions"><button class="btn sm" onclick="togglePin(${i})">${r.pinned?'Открепить':'Закрепить'}</button><button class="btn sm" onclick="toggleHide(${i})">${r.hidden?'Показать':'Скрыть'}</button>${r.pinned?`<button class="btn sm" onclick="movePin(${i},-1)">↑</button><button class="btn sm" onclick="movePin(${i},1)">↓</button>`:''}</div></div>`).join(''):'<div class="muted">Отзывов пока нет.</div>'}
window.togglePin=async i=>{data.reviews[i].pinned=!data.reviews[i].pinned;if(data.reviews[i].pinned)data.reviews[i].pinOrder=Math.max(0,...data.reviews.filter(x=>x.pinned).map(x=>Number(x.pinOrder)||0))+1;await save()};window.toggleHide=async i=>{data.reviews[i].hidden=!data.reviews[i].hidden;await save()};window.movePin=async(i,dir)=>{const pins=data.reviews.filter(x=>x.pinned).sort((a,b)=>(a.pinOrder||0)-(b.pinOrder||0)),r=data.reviews[i],p=pins.indexOf(r),q=p+dir;if(q<0||q>=pins.length)return;const t=r.pinOrder;r.pinOrder=pins[q].pinOrder;pins[q].pinOrder=t;await save()};
function render(){if(inst?.stop)inst.stop();const el=$('preview');el.innerHTML='';collect();const publicData=data.source.type==='yandex-live'?{mode:'yandex-live',source:data.source,design:data.design,content:data.content}:{mode:'managed',reviews:(data.reviews||[]).filter(r=>!r.hidden),design:data.design,content:data.content};inst=UniversalReviews.mount(el,publicData)}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function applyPreset(name){if(name!=='etnika')return;data.design={...(data.design||{}),layout:'slider',columns:3,gap:16,radius:0,maxWidth:1440,fontFamily:'Geologica,Arial,sans-serif',titleFontFamily:'Forum,Georgia,serif',titleSize:48,bodySize:16,cardPadding:24,buttonRadius:0,borderWidth:1,accent:'#981018',background:'#f5f3f2',cardBackground:'#ffffff',textColor:'#0a0a0a',mutedColor:'#6f6f6f',borderColor:'#0a0a0a',starColor:'#981018',minRating:1,showAvatar:true,showDate:true,showSource:true,showSummary:true,autoplay:true,yandexHeight:620};fill();render();setStatus('Пресет ETNIKA применён. Все параметры можно менять вручную.','ok')}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('on',x===b));document.querySelectorAll('.pane').forEach(p=>p.classList.toggle('on',p.dataset.pane===b.dataset.tab))});$('preset').onchange=()=>applyPreset($('preset').value);$('sourceType').onchange=()=>{sourceUI();render()};$('save').onclick=()=>save().catch(e=>setStatus(e.message,'err'));$('saveDesign').onclick=()=>save().catch(e=>setStatus(e.message,'err'));$('sync').onclick=sync;$('reload').onclick=load;$('embed').onclick=()=>{collect();const id='demo',base=STATIC_MODE?location.href.replace(/[^/]*$/,''):`${location.origin}/`;const publicData=data.source.type==='yandex-live'?{mode:'yandex-live',source:data.source,design:data.design,content:data.content}:{mode:'managed',reviews:(data.reviews||[]).filter(r=>!r.hidden),design:data.design,content:data.content};const safeJson=JSON.stringify(publicData).replace(/</g,'\u003c');const code=`<div id="reviews-${id}"></div>\n<script src="${base}widget.js"><\/script>\n<script>UniversalReviews.mount('#reviews-${id}', ${safeJson});<\/script>`;$('code').textContent=code;$('code').classList.toggle('on')};[...designKeys,'title','subtitle','buttonText','buttonUrl','showAvatar','showDate','showSource','showSummary','autoplay'].forEach(k=>$(k)?.addEventListener('input',render));load();