(function(){
'use strict';

const SCRIPT_BASE=(()=>{try{const src=document.currentScript&&document.currentScript.src;return src?new URL('.',src).href:null}catch{return null}})();
const D={
  layout:'slider',columns:3,tabletColumns:2,mobileColumns:1,gap:12,radius:14,maxWidth:1200,
  fontFamily:'inherit',titleFontFamily:'inherit',fontCssUrl:'',titleSize:38,bodySize:15,mobileTitleSize:30,bodyWeight:400,titleWeight:500,strongWeight:500,
  cardPadding:18,buttonRadius:10,borderWidth:1,accent:'#111111',background:'#ffffff',cardBackground:'#ffffff',
  textColor:'#202124',mutedColor:'#7a7d81',borderColor:'#e5e7eb',starColor:'#f5a623',minRating:1,
  sort:'newest',showAvatar:true,showDate:true,showSource:true,showRating:true,showSummary:true,
  showReviewButton:true,showControls:true,showBusinessResponse:true,showReactions:true,showMedia:true,
  maxTextLines:6,autoplay:true,autoplayDelay:4500,transitionMs:320,loop:true,yandexHeight:620,
  gridInitialItems:6,listInitialItems:3,loadMoreStep:6
};
const C={title:'Отзывы клиентов',subtitle:'Яндекс Карты',buttonText:'Оставить отзыв',buttonUrl:'',showHeader:true};
const sourceLabels={yandex:'Яндекс Карты'};

function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]))}
function safeUrl(u){try{const x=new URL(u,location.href);return ['http:','https:'].includes(x.protocol)?x.href:'#'}catch{return '#'}}
function mediaUrl(u){return String(u||'').replace('{size}','M').replace('%s','M')}
function dateLabel(v){if(!v)return'';const d=new Date(v);return isNaN(d)?'':new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric'}).format(d)}
function ratingLabel(v){const n=Number(v)||0;return new Intl.NumberFormat('ru-RU',{minimumFractionDigits:1,maximumFractionDigits:1}).format(n)}
function stars(n){const r=Math.max(0,Math.min(5,Math.round(Number(n)||0)));return `<span class="urw-stars" aria-label="${r} из 5">${'★'.repeat(r)}${'☆'.repeat(5-r)}</span>`}
function initials(s){return esc(String(s||'К').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase())}
function ensureFont(url){
  if(!url)return Promise.resolve();
  const key='urw-font-'+btoa(unescape(encodeURIComponent(url))).replace(/[^a-z0-9]/gi,'').slice(-18);
  const existing=document.getElementById(key);
  if(existing)return Promise.resolve();
  return new Promise(resolve=>{const l=document.createElement('link');l.id=key;l.rel='stylesheet';l.href=url;l.onload=()=>resolve();l.onerror=()=>resolve();document.head.appendChild(l);setTimeout(resolve,2500)})
}
function inject(){
  if(document.getElementById('urw-v8-style'))return;
  const s=document.createElement('style');s.id='urw-v8-style';s.textContent=`
.urw{--u-font:inherit;--u-title-font:inherit;--u-title-size:38px;--u-mobile-title-size:30px;--u-body-size:15px;--u-body-weight:400;--u-title-weight:500;--u-strong-weight:500;--u-card-pad:18px;--u-accent:#111;--u-bg:#fff;--u-card:#fff;--u-text:#202124;--u-muted:#7a7d81;--u-border:#e5e7eb;--u-border-width:1px;--u-star:#f5a623;--u-radius:14px;--u-button-radius:10px;--u-gap:12px;--u-cols:3;--u-cols-tablet:2;--u-cols-mobile:1;--u-max:1200px;--u-transition:320ms;font-family:var(--u-font);font-weight:var(--u-body-weight);color:var(--u-text);background:var(--u-bg);width:100%;height:auto!important;min-height:0!important;container-type:inline-size}
.urw *{box-sizing:border-box}.urw-shell{max-width:var(--u-max);margin:auto;padding:16px 0;height:auto;min-height:0}.urw-head{display:flex;justify-content:space-between;gap:24px;align-items:end;margin-bottom:16px}.urw-kicker{font-size:13px;color:var(--u-muted);margin-bottom:4px}.urw-title{font-family:var(--u-title-font);font-size:var(--u-title-size);font-weight:var(--u-title-weight);line-height:1.05;letter-spacing:-.03em;margin:0}.urw-summary{display:flex;align-items:center;gap:7px;flex-wrap:wrap;margin-top:8px;font-size:13px;color:var(--u-muted)}.urw-score{font-weight:700;color:var(--u-text);font-size:16px}.urw-stars{letter-spacing:.5px;color:var(--u-star);white-space:nowrap}.urw-btn{display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:0 16px;border:var(--u-border-width) solid var(--u-accent);background:var(--u-accent);color:#fff;text-decoration:none;border-radius:var(--u-button-radius);font-size:13px;font-weight:var(--u-strong-weight)}.urw-viewport{overflow:hidden;height:auto}.urw-track{display:flex;gap:var(--u-gap);align-items:flex-start;transition:transform var(--u-transition) ease}.urw-track .urw-card{min-width:calc((100% - (var(--u-cols) - 1)*var(--u-gap))/var(--u-cols))}.urw-grid{display:grid;grid-template-columns:repeat(var(--u-cols),minmax(0,1fr));gap:var(--u-gap);align-items:start}.urw-list{display:grid;grid-template-columns:1fr;gap:var(--u-gap);align-items:start}
.urw-card{border:var(--u-border-width) solid var(--u-border);border-radius:var(--u-radius);background:var(--u-card);padding:var(--u-card-pad);display:block;min-height:0;height:auto;box-shadow:0 1px 2px rgba(0,0,0,.02)}.urw-top{display:flex;align-items:center;gap:10px}.urw-avatar{position:relative;width:40px;height:40px;border-radius:50%;overflow:hidden;background:#f0f1f2;display:grid;place-items:center;font-size:12px;font-weight:700;flex:0 0 auto}.urw-avatar img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.urw-authorbox{min-width:0;flex:1}.urw-author{font-weight:var(--u-strong-weight);font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.urw-meta{font-size:12px;color:var(--u-muted);margin-top:2px;line-height:1.35}.urw-menu{margin-left:auto;color:var(--u-muted);font-size:18px;line-height:1}.urw-rating{margin:9px 0 7px;font-size:15px}.urw-text{font-size:var(--u-body-size);line-height:1.48;margin:0;white-space:pre-line;overflow:hidden}.urw-text.clamped{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:var(--u-lines,6)}.urw-more{border:0;background:transparent;color:var(--u-muted);font:var(--u-strong-weight) 12px var(--u-font);padding:4px 0 0;cursor:pointer;text-align:left}.urw-source{font-size:11px;color:var(--u-muted);text-decoration:none}.urw-media{display:flex;gap:6px;overflow:hidden;margin-top:10px}.urw-media-item{position:relative;width:76px;height:76px;border-radius:9px;overflow:hidden;background:#f2f2f2;display:block;flex:0 0 76px}.urw-media-item img{width:100%;height:100%;object-fit:cover;display:block}.urw-play{position:absolute;inset:0;display:grid;place-items:center;color:#fff;font-size:24px;background:rgba(0,0,0,.18)}
.urw-response{margin-top:10px;padding-top:9px;border-top:1px solid var(--u-border)}.urw-response summary{cursor:pointer;list-style:none;font-size:12px;font-weight:var(--u-strong-weight);color:var(--u-muted);user-select:none}.urw-response summary::-webkit-details-marker{display:none}.urw-response summary:before{content:'— ';color:var(--u-muted)}.urw-response[open] summary{margin-bottom:9px}.urw-response-head{display:flex;align-items:center;gap:8px;margin-bottom:6px}.urw-response-logo{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:#f1f1f1;font-size:11px;font-weight:700;overflow:hidden}.urw-response-logo img{width:100%;height:100%;object-fit:cover}.urw-response-title{font-size:12px;font-weight:var(--u-strong-weight)}.urw-response-date{font-size:11px;color:var(--u-muted)}.urw-response-text{font-size:13px;line-height:1.45;margin:0}.urw-foot{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:10px;padding-top:8px;border-top:1px solid rgba(0,0,0,.045)}.urw-reactions{display:flex;gap:12px;font-size:12px;color:var(--u-muted)}.urw-original{font-size:12px;color:var(--u-muted);text-decoration:none}.urw-controls{display:flex;justify-content:flex-end;gap:8px;margin-top:10px}.urw-arrow{width:38px;height:38px;border-radius:var(--u-button-radius);border:var(--u-border-width) solid var(--u-border);background:var(--u-card);color:var(--u-text);cursor:pointer}.urw-loadmore-wrap{text-align:center;margin-top:12px}.urw-loadmore{min-height:40px;padding:0 16px;border:var(--u-border-width) solid var(--u-border);background:var(--u-card);color:var(--u-text);border-radius:var(--u-button-radius);font:var(--u-strong-weight) 13px var(--u-font);cursor:pointer}.urw-empty{padding:28px;border:var(--u-border-width) dashed var(--u-border);border-radius:var(--u-radius);text-align:center;color:var(--u-muted)}.urw-yandex-wrap{overflow:hidden;border:var(--u-border-width) solid var(--u-border);border-radius:var(--u-radius);background:var(--u-card)}.urw-yandex{display:block;width:100%;border:0;min-height:500px}.urw-yandex-credit{display:block;text-align:center;color:var(--u-muted);font-size:10px;padding:7px 10px;text-decoration:none}.urw-live{font-size:12px;color:var(--u-muted);margin-top:8px}
@container (max-width:900px){.urw-track .urw-card{min-width:calc((100% - (var(--u-cols-tablet) - 1)*var(--u-gap))/var(--u-cols-tablet))}.urw-grid{grid-template-columns:repeat(var(--u-cols-tablet),minmax(0,1fr))}.urw-title{font-size:min(var(--u-title-size),34px)}}
@container (max-width:640px){.urw-head{display:grid;gap:14px}.urw-track .urw-card{min-width:calc((100% - (var(--u-cols-mobile) - 1)*var(--u-gap))/var(--u-cols-mobile))}.urw-grid{grid-template-columns:repeat(var(--u-cols-mobile),minmax(0,1fr))}.urw-title{font-size:var(--u-mobile-title-size)}.urw-shell{padding:12px 0}.urw-media-item{width:68px;height:68px;flex-basis:68px}}
`;
  document.head.appendChild(s)
}

class W{
  constructor(el,c){this.el=el;this.raw=c||{};this.i=0;this.timer=null;this.displayCount=null;inject();this.init()}
  async init(){
    let payload=this.raw;
    if(this.raw.widgetId||this.raw.apiUrl){
      const url=this.raw.apiUrl||`${this.raw.baseUrl||''}/api/widget/${encodeURIComponent(this.raw.widgetId)}`;
      const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`Reviews widget HTTP ${r.status}`);payload=await r.json()
    }
    if(payload.mode==='managed'&&SCRIPT_BASE){
      try{const r=await fetch(`${SCRIPT_BASE}data/reviews.json?v=${Date.now()}`,{cache:'no-store'});if(r.ok){const j=await r.json();payload={...payload,summary:payload.summary||j.summary,profile:payload.profile||j.profile}}}catch{}
    }
    this.payload=payload;this.design={...D,...(payload.design||{}),...(this.raw.design||{})};this.content={...C,...(payload.content||{}),...(this.raw.content||{})};
    await ensureFont(this.design.fontCssUrl);if(document.fonts?.ready)try{await document.fonts.ready}catch{}this.apply();this.render();this.start();
    if('ResizeObserver'in window){this.ro=new ResizeObserver(()=>{if(this.design.layout==='slider')this.go(this.i)});this.ro.observe(this.el)}
  }
  apply(){
    const d=this.design,s=this.el.style;this.el.className='urw';
    s.setProperty('--u-font',d.fontFamily||'inherit');s.setProperty('--u-title-font',d.titleFontFamily||d.fontFamily||'inherit');s.setProperty('--u-title-size',`${Math.max(18,Number(d.titleSize)||38)}px`);s.setProperty('--u-mobile-title-size',`${Math.max(18,Number(d.mobileTitleSize)||30)}px`);s.setProperty('--u-body-size',`${Math.max(12,Number(d.bodySize)||15)}px`);s.setProperty('--u-body-weight',String(Math.max(100,Math.min(900,Number(d.bodyWeight)||400))));s.setProperty('--u-title-weight',String(Math.max(100,Math.min(900,Number(d.titleWeight)||500))));s.setProperty('--u-strong-weight',String(Math.max(100,Math.min(900,Number(d.strongWeight)||500))));s.setProperty('--u-card-pad',`${Math.max(0,Number(d.cardPadding)||18)}px`);s.setProperty('--u-accent',d.accent);s.setProperty('--u-bg',d.background);s.setProperty('--u-card',d.cardBackground);s.setProperty('--u-text',d.textColor);s.setProperty('--u-muted',d.mutedColor||D.mutedColor);s.setProperty('--u-border',d.borderColor);s.setProperty('--u-border-width',`${Math.max(0,Number(d.borderWidth)||0)}px`);s.setProperty('--u-star',d.starColor||D.starColor);s.setProperty('--u-radius',`${Math.max(0,Number(d.radius)||0)}px`);s.setProperty('--u-button-radius',`${Math.max(0,Number(d.buttonRadius)||0)}px`);s.setProperty('--u-gap',`${Math.max(0,Number(d.gap)||0)}px`);s.setProperty('--u-cols',Math.max(1,Math.min(5,Number(d.columns)||1)));s.setProperty('--u-cols-tablet',Math.max(1,Math.min(4,Number(d.tabletColumns)||2)));s.setProperty('--u-cols-mobile',Math.max(1,Math.min(2,Number(d.mobileColumns)||1)));s.setProperty('--u-max',`${Math.max(320,Number(d.maxWidth)||1200)}px`);s.setProperty('--u-transition',`${Math.max(80,Number(d.transitionMs)||320)}ms`)
  }
  header(summaryHtml=''){const c=this.content;if(c.showHeader===false)return'';return `<div class="urw-head"><div><div class="urw-kicker">${esc(c.subtitle)}</div><h2 class="urw-title">${esc(c.title)}</h2>${summaryHtml}</div>${this.design.showReviewButton&&c.buttonUrl?`<a class="urw-btn" href="${esc(safeUrl(c.buttonUrl))}" target="_blank" rel="noopener">${esc(c.buttonText)}</a>`:''}</div>`}
  render(){if(this.payload.mode==='yandex-live')return this.renderYandex();this.renderManaged(true)}
  renderYandex(){const p=this.payload,d=this.design,id=String(p.source?.businessId||'');const src=`https://yandex.ru/maps-reviews-widget/${encodeURIComponent(id)}?comments`;const org=safeUrl(p.source?.businessUrl||`https://yandex.ru/maps/org/${encodeURIComponent(id)}/reviews/`);this.el.innerHTML=`<div class="urw-shell">${this.header(`<div class="urw-live">Обновляется напрямую из Яндекс Карт</div>`)}<div class="urw-yandex-wrap"><iframe class="urw-yandex" style="height:${Math.max(500,Number(d.yandexHeight)||620)}px" loading="lazy" src="${esc(src)}"></iframe><a class="urw-yandex-credit" href="${esc(org)}" target="_blank" rel="noopener">Открыть организацию на Яндекс Картах ↗</a></div></div>`}
  prep(){const d=this.design;let a=(this.payload.reviews||[]).filter(r=>Number(r.rating||0)>=Number(d.minRating||0));if(d.sort==='newest')a.sort((x,y)=>new Date(y.date||0)-new Date(x.date||0));if(d.sort==='oldest')a.sort((x,y)=>new Date(x.date||0)-new Date(y.date||0));if(d.sort==='rating')a.sort((x,y)=>Number(y.rating||0)-Number(x.rating||0));if(d.sort==='random')a.sort(()=>Math.random()-.5);a.sort((x,y)=>Number(Boolean(y.pinned))-Number(Boolean(x.pinned))||(Number(x.pinOrder)||0)-(Number(y.pinOrder)||0));return a}
  media(r){if(!this.design.showMedia)return'';const items=[];(r.photos||[]).forEach(p=>{const u=mediaUrl(p.url||p.urlTemplate);if(u)items.push(`<a class="urw-media-item" href="${esc(safeUrl(u))}" target="_blank" rel="noopener"><img loading="lazy" src="${esc(safeUrl(u))}" alt="Фото из отзыва"></a>`)});(r.videos||[]).forEach(v=>{const u=safeUrl(v.url||'#'),p=mediaUrl(v.preview||v.thumbnail||'');if(p)items.push(`<a class="urw-media-item" href="${esc(u)}" target="_blank" rel="noopener"><img loading="lazy" src="${esc(safeUrl(p))}" alt="Видео из отзыва"><span class="urw-play">▶</span></a>`)});return items.length?`<div class="urw-media">${items.slice(0,5).join('')}</div>`:''}
  response(r){const b=r.businessResponse;if(!this.design.showBusinessResponse||!b||!b.text)return'';const logo=this.payload.profile?.logo;return `<details class="urw-response"><summary>Посмотреть ответ организации</summary><div class="urw-response-head"><div class="urw-response-logo">${logo?`<img src="${esc(safeUrl(mediaUrl(logo)))}" alt="">`:'О'}</div><div><div class="urw-response-title">Ответ организации</div>${b.date?`<div class="urw-response-date">${esc(dateLabel(b.date))}</div>`:''}</div></div><p class="urw-response-text">${esc(b.text)}</p></details>`}
  card(r,idx){const d=this.design,lines=Math.max(3,Number(d.maxTextLines)||6),hasText=String(r.text||'').length>170;return `<article class="urw-card"><div class="urw-top">${d.showAvatar?`<div class="urw-avatar">${r.avatar?`<img loading="lazy" src="${esc(safeUrl(r.avatar))}" alt="" onerror="this.remove()">`:initials(r.author)}</div>`:''}<div class="urw-authorbox"><div class="urw-author">${esc(r.author||'Пользователь Яндекса')}</div><div class="urw-meta">${r.authorLevel?esc(r.authorLevel):''}${r.authorLevel&&d.showDate?' · ':''}${d.showDate?esc(dateLabel(r.date)):''}</div></div><span class="urw-menu">⋯</span></div>${d.showRating?`<div class="urw-rating">${stars(r.rating)}</div>`:''}<p class="urw-text ${hasText?'clamped':''}" data-text="${idx}" style="--u-lines:${lines}">${esc(r.text||'')}</p>${hasText?`<button class="urw-more" type="button" data-more="${idx}">Ещё</button>`:''}${this.media(r)}${this.response(r)}<div class="urw-foot">${d.showReactions?`<div class="urw-reactions"><span>♡ ${Number(r.likes)||''}</span><span>♧ ${Number(r.dislikes)||''}</span></div>`:'<span></span>'}${d.showSource&&r.url?`<a class="urw-original" href="${esc(safeUrl(r.url))}" target="_blank" rel="noopener">${esc(sourceLabels[r.source]||'Яндекс Карты')} ↗</a>`:''}</div></article>`}
  renderManaged(reset=false){
    this.reviews=this.prep();const official=this.payload.summary||null;const fallbackAvg=(this.payload.reviews||[]).length?((this.payload.reviews||[]).reduce((s,r)=>s+Number(r.rating||0),0)/(this.payload.reviews||[]).length):0;const avg=official&&official.rating!=null?Number(official.rating):fallbackAvg;const reviewCount=official&&official.reviewsCount!=null?Number(official.reviewsCount):(this.payload.reviews||[]).length;const ratingsCount=official&&official.ratingsCount!=null?Number(official.ratingsCount):null;const countText=ratingsCount!=null?`${reviewCount} отзывов · ${ratingsCount} оценок`:`${reviewCount} отзывов`;const summary=this.design.showSummary?`<div class="urw-summary"><span class="urw-score">${ratingLabel(avg)}</span>${stars(avg)}<span>${countText}</span></div>`:'';
    const layout=this.design.layout;
    if(reset||this.displayCount==null){this.displayCount=layout==='grid'?Math.max(1,Number(this.design.gridInitialItems)||6):layout==='list'?Math.max(1,Number(this.design.listInitialItems)||3):this.reviews.length}
    const shown=layout==='slider'?this.reviews:this.reviews.slice(0,this.displayCount);const cls=layout==='grid'?'urw-grid':layout==='list'?'urw-list':'urw-track';const more=layout!=='slider'&&shown.length<this.reviews.length?`<div class="urw-loadmore-wrap"><button class="urw-loadmore" type="button" data-loadmore>Показать ещё</button></div>`:'';
    this.el.innerHTML=`<div class="urw-shell">${this.header(summary)}${shown.length?`<div class="${layout==='slider'?'urw-viewport':''}"><div class="${cls}" data-track>${shown.map((r,i)=>this.card(r,i)).join('')}</div></div>`:`<div class="urw-empty">Нет отзывов для выбранного фильтра.</div>`}${layout==='slider'&&this.design.showControls&&shown.length>1?`<div class="urw-controls"><button class="urw-arrow" data-prev aria-label="Предыдущие отзывы">←</button><button class="urw-arrow" data-next aria-label="Следующие отзывы">→</button></div>`:''}${more}</div>`;
    this.bindCommon();if(layout==='slider')this.bindSlider();this.el.querySelector('[data-loadmore]')?.addEventListener('click',()=>{this.displayCount+=Math.max(1,Number(this.design.loadMoreStep)||6);this.renderManaged(false)})
  }
  bindCommon(){this.el.querySelectorAll('[data-more]').forEach(b=>b.addEventListener('click',()=>{const t=this.el.querySelector(`[data-text="${b.dataset.more}"]`);if(!t)return;const open=t.classList.toggle('expanded');t.classList.toggle('clamped',!open);b.textContent=open?'Свернуть':'Ещё'}))}
  desktopCols(){return Math.max(1,Math.min(5,Number(this.design.columns)||1))} tabletCols(){return Math.max(1,Math.min(4,Number(this.design.tabletColumns)||2))} mobileCols(){return Math.max(1,Math.min(2,Number(this.design.mobileColumns)||1))}
  visible(){const w=this.el.getBoundingClientRect().width;return w<=640?this.mobileCols():w<=900?this.tabletCols():this.desktopCols()}
  max(){return Math.max(0,(this.reviews?.length||0)-this.visible())}
  bindSlider(){this.track=this.el.querySelector('[data-track]');this.el.querySelector('[data-prev]')?.addEventListener('click',()=>this.go(this.i-1,true));this.el.querySelector('[data-next]')?.addEventListener('click',()=>this.go(this.i+1,true));this.go(0)}
  go(n,user=false){if(!this.track)return;const max=this.max();if(this.design.loop){if(n<0)n=max;if(n>max)n=0}else n=Math.max(0,Math.min(max,n));this.i=n;const first=this.track.children[0];if(first)this.track.style.transform=`translate3d(-${(first.getBoundingClientRect().width+Number(this.design.gap||0))*n}px,0,0)`;if(user){this.stop();this.start()}}
  start(){this.stop();if(this.payload.mode!=='managed'||this.design.layout!=='slider'||!this.design.autoplay||this.max()===0)return;this.timer=setInterval(()=>this.go(this.i+1),Math.max(1200,Number(this.design.autoplayDelay)||4500))}
  stop(){if(this.timer)clearInterval(this.timer);this.timer=null}
  destroy(){this.stop();this.ro?.disconnect()}
}
window.UniversalReviews={mount(target,c){const el=typeof target==='string'?document.querySelector(target):target;if(!el)throw new Error('Widget target not found');return new W(el,c)},mountAll(){document.querySelectorAll('[data-universal-reviews]').forEach(el=>{let c={};try{c=JSON.parse(el.getAttribute('data-config')||'{}')}catch{};window.UniversalReviews.mount(el,c)})}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>window.UniversalReviews.mountAll());else window.UniversalReviews.mountAll();
})();